# Generated by Django 5.1.5 on 2025-02-04 11:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_favoritebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritebook',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
